
services:
  doxygen:
    build: .
    image: ofr_doxygen
    volumes:
      - ../:/doxygen
    command: >
        PROJECT_NAME="Open Font Render"
        PROJECT_NUMBER=1.1
        HTML_OUTPUT="docs"
        OUTPUT_LANGUAGE=Japanese-en
        GENERATE_TREEVIEW=YES
        MARKDOWN_SUPPORT=YES
        GENERATE_LATEX=NO
        GENERATE_XML=YES
        HTML_COLORSTYLE=TOGGLE
        USE_MDFILE_AS_MAINPAGE="README.md"
        HTML_EXTRA_STYLESHEET=./doxygen/doxygen-awesome-css/doxygen-awesome.css
        INPUT="
          ./README.md \
          ./REFERENCE_SITES.md \
          ./src/module_description.h \
          ./src/OpenFontRender.cpp \
          ./src/OpenFontRender.h \
          ./src/FileSupport.cpp \
          ./src/FileSupport.h \
          "
    container_name: ofr-doc-container
